sonar.projectKey=dindin-exe-frontend
sonar.projectName=DinDin.exe Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/main.tsx,src/assets/**
sonar.sourceEncoding=UTF-8
